repos:
# Common hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-yaml

# Terraform specific hooks
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.58.0
  hooks:
  - id: terraform_docs
  - id: terraform_tfsec
  - id: terraform_tflint
