######################################################
# Terraform Plan Workflow
# 
# Performs a plan when a PR is triggered to show
# changes before approval
######################################################

name: Terraform - Plan

# set global pipeline env vars
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.2.4

# workflow triggers
on:
  # enables manual runs
  workflow_dispatch:
  # on pr to main
  pull_request:
    branches: [ main ]
    paths: [ '**.tf' ]

# workflow
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2

    # setup
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # base checks
    - name: terraform fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: terraform init
      run: terraform init
    - name: terraform validate
      run: terraform validate

    # plan
    - name: terraform plan
      run: terraform plan -out tf.plan
