name: Terraform - Apply

# set global pipeline env vars
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.2.4
  ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

# workflow triggers
on:
  # enables manual runs
  workflow_dispatch:
  # on push to main
  push:
    branches: [ main ]
    paths:
    - '**.tf'
    - '**.tfvars'

# workflow
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2

    # setup
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # base checks
    - name: terraform fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: terraform init
      run: terraform init
    - name: terraform validate
      run: terraform validate

    # plan
    - name: terraform plan
      run: terraform plan -out tf.plan
      
    # upload plan
    - name: upload artifact
      uses: actions/upload-artifact@3.1.0
      with:
        name: plan
        path: .
        retention-days: 1
      
  apply:
    runs-on: ubuntu-latest
    needs: [ plan ]
    environment: dev
    steps:
    # download artifact
    - name: download plan
      uses: actions/download-artifact@3.0.0
      with:
        name: plan
        path: .
    
    # setup
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # apply
    - name: terraform apply
      run: terraform apply tf.plan
